name: OpenWrt Builder

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: /workdir

    steps:
      - name: Create workdir
        working-directory: /
        run: |
          sudo mkdir -p /workdir
          sudo chown $USER:$GROUPS /workdir
      
      - name: Cleanup disk
        uses: eclipse-score/more-disk-space@v1.1
        with:
          level: 4
      
      - name: Cache dl directory
        uses: actions/cache@v4
        with:
          path: openwrt/dl
          key: ${{ runner.os }}-openwrt-dl-${{ hashFiles('openwrt/.config') }}
          restore-keys: |
            ${{ runner.os }}-openwrt-dl-
      
      - name: Setup build environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo apt update
          sudo apt install -y --no-install-recommends \
              make gcc g++ gcc-aarch64-linux-gnu \
              libncurses-dev zlib1g-dev libssl-dev \
              unzip bzip2 swig bison flex \
              python3-distutils python3-setuptools
      
      - name: Clone source
        run: |
          git clone -b v25.12.1 --depth 1 https://github.com/immortalwrt/immortalwrt /workdir/openwrt
      
      - name: Install feeds
        run: |
          cd /workdir/openwrt 
          ./scripts/feeds update -a 
          ./scripts/feeds install -a
      
      - name: Patch source
        run: |
          cd /workdir/openwrt 
          cp ./target/linux/mediatek/dts/mt7981b-cmcc-rax3000m-nand.dtso ./target/linux/mediatek/dts/mt7981b-cmcc-rax3000m-nand-256m.dtso
          sed -i 's/reg = <0x580000 0x7200000>;/reg = <0x580000 0xEE00000>;/' ./target/linux/mediatek/dts/mt7981b-cmcc-rax3000m-nand-256m.dtso
          sed -i '/DEVICE_DTS_OVERLAY := mt7981b-cmcc-rax3000m-emmc mt7981b-cmcc-rax3000m-nand/s/$/ mt7981b-cmcc-rax3000m-nand-256m/' ./target/linux/mediatek/image/filogic.mk
          sed -i 's/--set=llvm\.download-ci-llvm=true/--set=llvm.download-ci-llvm=false/' ./feeds/packages/lang/rust/Makefile
      
      - name: Checkout config file
        uses: actions/checkout@main
      
      - name: Copy config to soutce
        run: |
          cd /workdir/openwrt 
          cp ${GITHUB_WORKSPACE}/config_RAC3000M .config
      
      # - name: Build image
      #   run: |
      #     cd /workdir/openwrt 
      #     make defconfig
      #     make download -j8
      #     make -j4 || make -j2 || make -j1 V=s
      #     echo "BUILD_STATUS=success" >> $GITHUB_ENV
      
      - name: Prepare upload file
        # if: env.BUILD_STATUS == 'success' && !cancelled()
        run: |
          cd /workdir/openwrt 
          tar -zcvf upload.tar.gz --exclude=packages .config
          echo "TAG_NAME=OpenWrt_$(date +"%Y%m%d%H%M")" >> $GITHUB_ENV
          echo "UPLOAD_FILE=$PWD/upload.tar.gz"
      
      - name: Upload firmware to release
        uses: softprops/action-gh-release@v3
        # if: env.BUILD_STATUS == 'success' && !cancelled()
        with:
          tag_name: ${{ env.TAG_NAME }}
          files: ${{ env.UPLOAD_FILE }}
